### ISSUE TITLE
Thank you, and a Favor

### ISSUE THREAD

**Issue by nathanRamaNoodles** [DLehenbauer/arduino-midi-sound-module#2]
I've seen your demo and was amazed that you perfected this feat on an Arduino Uno! 
Since your code didn't get the respect it deserved I posted this project on [reddit and it was popular](https://www.reddit.com/r/arduino/comments/8oi1th/someone_pinch_me_this_guy_made_16_note_polyphonic/?utm_content=full_comments&utm_medium=message&utm_source=reddit&utm_name=frontpage).
Your welcome.
Also, I can see potential in your project.  I just have one favor; is there a way you could make the code to read a MIDI file from an SD card?  If so, then that would really make the Arduino community happy.

Thank you for your time.

**Comment by DLehenbauer** [comment]
Thanks for the enthusiasm!

Embedding the MIDI file or reading from an SD card would be an interesting challenge.  As-is, the project does a pretty good job of utilizing every available resource of the Uno.  :)

Most of the MIDIs in my collection exceed the available memory on the Uno, so an SD card is probably the way to go.

The easiest solution would be to use a second Uno to play back the SMF, connecting serial out of the player to serial in of the synth.  (That by itself could be an interesting and useful stand alone project.)

Play back using a single Uno would require making some tradeoffs to free resources.  Here are some things I've considered or experimented with along the way:
* Reduce to 12 voices.  (Many MIDI files still play reasonably well w/12 note polyphony)
* Drop the OLED display.  (Neat demo, but may not be useful to the community.)
* Reduce the size of the wavetable by increasing reuse between instruments to free PRGMEM.
* Less convenient representation of envelope programs to reduce calculation cost.
* Share a single modulator for frequency/wavetable offset envelopes.  (Few instruments use both)
* Lowering the sample playback rate.

There are opportunities to preprocessing midi files to coalesce high frequency state changes, premultiply velocity and channel volume, filter unused data, etc. to compress and simplify playback.

A few more ideas that I think would be fun, but would make the project generally less accessible:
* Custom firmware on the 16u2 to preprocess midi (e.g., coalesce/premultiply pitch bends)
* Increase clock from 16 -> 20mhz by building on a breadboard.  (Uno is underclocked)
* Drop support for the Arduino IDE and/or distribute as precompiled binary.

(And of course, there's always the option of moving to a Teensy or Pi Zero...  but just seems too easy.  :)

Personally, I was posting the source/video because I didn't anticpate having time to tinker w/this project for a while, but it sounds like a really fun place to pick up again!  (Or a fun place for a collaborator to join. :D)

**Comment by nathanRamaNoodles** [comment]
## My Background 
Yeah, I love to tinker with Arduinos and play music with them.  Personally, my main goal was to make an Arduino mp3 player with skipping, pause/play and timing functionality.  Essentially, the arduino needs a library that allows it to play a music file(without the help of a computer), out to a speaker with polyphony.  The raspberry Pi already does this, so I want the Arduino to at least have some way to play polyphonic music in a crystal quality. I was interested in more voices but never had the ambition to learn assembly because...C++ is where it's at 😂.

  I'm a noob when it comes to timers and wavetable synthesis; I'm more comfortable with dealing with the aspect of time in general.  For example, in my MusicWithoutDelay library, I tested and came up with formulas that allowed me to pause during a song, without delay(non-blocking) :D 
 
   I got more interested in time managing, so I tried to see if I could try skipping anywhere within the song.  So I did.  While I was there I got bored and made a function to play the music backward.  Yeah, I didn't know how to store MIDI files to an SD card and read it to the Arduino, so I used the most basic form of music files...RTTL(Ring Tone Transfer Language).  I never felt like going back to maintaining the library because not many people saw its usefulness.  I have better code that allows me to store the RTTL files to PROGMEM, and have used this [synth library](https://github.com/dzlonline/the_synth) to allow tetrapolyphony.  If your interested, I can update **the files on my Github for you to test**(I got Legend of Zelda I wrote by hand😫).

## Ok
Anyways, I'd love to be a collaborator for your project.  I'm still in college, but its something fun to do over the summer.  

I still can't believe you managed to pull 16 note polyphony on a weak board like the Arduino.  I wonder what you'll do on the Arm Cortex MCU 😂.

I tried to read your code, and found a [library that allows reading MIDI files from an SD card](https://github.com/5shekel/midi.player).  But I had a hard time implementing it in your code.  **And Yes, we could send instruments.h to the SD card,** seems to eat the most memory.  A while ago, I figured out we can open multiple files at the same time, it takes 512 bytes of SRAM for one SD file, and then 50 bytes for every additional file opened.

**Comment by DLehenbauer** [comment]
I was thinking the SMF (aka MIDI file) would need to go on the SD card.  The wavetable in instruments probably needs to stay in PRGMEM.  (We need to sample 16 x 256B waveforms in real-time in the sample/mix ISR, and there isn't enough SRAM to cache these from the SD card.)

The library you found would complete the other side of a two Arduino solution, where one Arduino produces MIDI messages by playing back an SMF from an SD card, and the other generates sound from incoming MIDI messages (just connect TX to RX).
