### ISSUE TITLE
Display behaves differently on first play of midifile compared to subsequent plays

### ISSUE THREAD

**Issue by urbantigerau** [DLehenbauer/arduino-midi-sound-module#6]
Hi,
Firstly thank you for developing this software. Given the hardware it runs on it is a remarkable achievement and it works really well. 

I am working on a clock which I want to play the Westminster chimes, as per Big Ben in London, England. Having the clock play the respective MIDI files is a pleasing solution in terms of ability to get a good sound and be able to modify it. Your software makes that a proposition at a very reasonable cost compared to some of the Arduino MIDI solutions.

In the process of development I have encountered an odd phenomenon with the behavior of the display.

Please see the attached file which plays the hour chime melody followed by 6 hour strikes.  While I probably won't use the display in final implementation I am having trouble seeing why the display behaves as it does.
[west.zip](https://github.com/DLehenbauer/arduino-midi-sound-module/files/4304561/west.zip)

I am playing this file with Audacity configured to play into the LoopMIDI port then through the Hairless MIDI Serial Bridge to the Arduino which is on USB Port 7. The file plays as expected and sounds good. It is a very simple melody, effectively no chords and only one note at a time. The first time it plays the display shows notes sequentially across the voices as the notes play. First note shows on first voice, second on second voice and so on, until the 16 notes of the melody play out and all the hour strikes show on the first voice. 

On all subsequent plays (until the Arduino is reset) the display shows notes on the first and second voices alternately, with the hour strike being on the first voice.

On first glance this looks like an initialization problem, and I started to look for that in the code. However this code, even the display part which is simpler, is complex as necessitated by what it does in such simple hardware. It seems to me that the display side of the code is correct and it is correctly reporting that each note is on a different voice for the first play. I cannot see why that is given the debug information from Hairless. See the attached image showing all notes going to channel 1.
![west](https://user-images.githubusercontent.com/2404001/76182195-c78a9100-620f-11ea-9577-be1d8af157e2.jpg)

I admit that this is not a desperate problem, but it is an interesting one and I hope you have the time to have a look. 

Once again thanks for taking the time to develop such a great piece of software. 

Kind Regards,
Fred.

**Comment by DLehenbauer** [comment]
I'm glad to hear that you're enjoying the synthesizer!

You're correct that initialization is involved, but I think what probably makes the current behavior surprising is that the display is showing the amplitude of synthesizer voices, not MIDI channels.

A MIDI channel is roughly equivalent to an instrument.  One MIDI channel may play multiple notes simultaneously.

A synthesizer voice is an independent sound generator.  This synthesizer has 16 voices, which means it can play 16 notes simultaneously.

However, there is no practical limit on the number of notes a MIDI file may play simultaneously.  To handle this, synthesizers typically employ a [voice-stealing](https://www.sweetwater.com/insync/voice-stealing/)  heuristic.

The phenomena you're observing on the display is the output of this synthesizer's voice-stealing heuristic (see `getNextVoice()` in synth.h).

Initially, each voice has been "finished forever", so the heuristic prefers voices that have never been played.  After each voice has been played once, they begin to tie.

The reason you see some alternation between voices 1 & 2 is because after the `note off` messages, there is still a little bit of decay, so the note isn't quite finished yet.

(Hope this makes sense.)

For your application, you might find some of the following changes helpful:
- Reducing the number of voices to free up CPU cycles (if needed)
- Trimming the data in instruments_generated.h to free up flash memory (if needed)

Let me know if you'd like any tips on how to do that...  and good luck with your project!

Daniel

**Comment by urbantigerau** [comment]
Thanks for you kind and informative reply Daniel, especially related to my project. The subtlety of voices vs channels is one I had missed but explains a lot. I have been referencing available  MIDI documents (like  http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html and https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message) about file structure and had missed the voice concept and the relationship to channels. I will study it closely again.  I am sure I can learn more.

I particularly like the voice stealing behavior, very subtle. Your explanation completely describes the behavior I have observed. It would probably not perplex anyone with a more complex melody. It really only stands out with the simple chime I am using.  

Thanks for the offer of trimming and reducing CPU cycles, I will take you up on it if I need that. 

Again thanks for responding. I may have another question about silencing in mid-stream. If so I will open another issue as this is the best way for others to benefit from questions and the answers.

Thanks again for your assistance.

Regards,
Fred.

**Comment by urbantigerau** [comment]
Hi Daniel,

I have replied on GITHUB to close the issue. Again thanks for a great explanation. I am contemplating another issue regarding silencing the snyth mid-stream but I may be able to sort it myself yet.

Please see attached document as regards the project I referred to.

I have attached a sound file so you can hear it as it is as described above

Thanks again for your assistance.

Regards, Fred.
